/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MainWindowRouteImport } from './routes/main-window'

const MainWindowRoute = MainWindowRouteImport.update({
  id: '/main-window',
  path: '/main-window',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/main-window': typeof MainWindowRoute
}
export interface FileRoutesByTo {
  '/main-window': typeof MainWindowRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/main-window': typeof MainWindowRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/main-window'
  fileRoutesByTo: FileRoutesByTo
  to: '/main-window'
  id: '__root__' | '/main-window'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MainWindowRoute: typeof MainWindowRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/main-window': {
      id: '/main-window'
      path: '/main-window'
      fullPath: '/main-window'
      preLoaderRoute: typeof MainWindowRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  MainWindowRoute: MainWindowRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
